# Generated by Django 5.2.13 on 2026-04-12 01:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(help_text="e.g. 'api.openai.com'", max_length=255)),
                ('name', models.CharField(help_text="Human-readable name, e.g. 'OpenAI'", max_length=255)),
                ('purpose', models.TextField(blank=True, help_text='User-annotated purpose of this service')),
                ('first_seen_at', models.DateTimeField(help_text='When this service was first observed in traffic')),
                ('last_seen_at', models.DateTimeField(help_text='When this service was last observed in traffic')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'External Service',
                'verbose_name_plural': 'External Services',
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('tenant', 'domain')},
            },
        ),
    ]
