# Generated by Django 5.2.13 on 2026-04-12 01:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wiregraph_egress', '0001_initial'),
        ('wiregraph_tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Machine-readable name, e.g. 'email_address'", max_length=255)),
                ('label', models.CharField(help_text="Human-readable label, e.g. 'Email Address'", max_length=255)),
                ('sensitivity_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='wiregraph_tenants.tenant')),
            ],
            options={
                'verbose_name': 'Data Asset',
                'verbose_name_plural': 'Data Assets',
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DataEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('wiregraph_egress', 'Egress')], max_length=20)),
                ('endpoint', models.CharField(help_text="Request path, e.g. '/api/users/'", max_length=2048)),
                ('method', models.CharField(help_text="HTTP method, e.g. 'GET', 'POST'", max_length=10)),
                ('detection_method', models.CharField(choices=[('regex', 'Regex'), ('presidio', 'Presidio')], max_length=20)),
                ('redacted_snippet', models.TextField(blank=True, help_text='Redacted or hashed PII context — never stores raw PII')),
                ('confidence', models.FloatField(default=1.0, help_text='Detection confidence score (0.0 to 1.0)')),
                ('request_id', models.CharField(blank=True, help_text='Optional correlation ID for grouping events from a single request', max_length=255)),
                ('timestamp', models.DateTimeField(help_text='When the PII was observed')),
                ('data_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='wiregraph_detection.dataasset')),
                ('external_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='wiregraph_egress.externalservice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='wiregraph_tenants.tenant')),
            ],
            options={
                'verbose_name': 'Data Event',
                'verbose_name_plural': 'Data Events',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', 'timestamp'], name='detection_d_tenant__574385_idx'), models.Index(fields=['tenant', 'data_asset'], name='detection_d_tenant__8bf8e7_idx'), models.Index(fields=['tenant', 'direction'], name='detection_d_tenant__868681_idx')],
            },
        ),
    ]
