# Generated by Django 5.2.13 on 2026-04-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiregraph_detection', '0003_dataevent_match_count'),
        ('wiregraph_tenants', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='allowlistrule',
            new_name='wiregraph_d_tenant__bf9538_idx',
            old_name='detection_a_tenant__ff7255_idx',
        ),
        migrations.RenameIndex(
            model_name='dataevent',
            new_name='wiregraph_d_tenant__81a5f9_idx',
            old_name='detection_d_tenant__574385_idx',
        ),
        migrations.RenameIndex(
            model_name='dataevent',
            new_name='wiregraph_d_tenant__422d9f_idx',
            old_name='detection_d_tenant__8bf8e7_idx',
        ),
        migrations.RenameIndex(
            model_name='dataevent',
            new_name='wiregraph_d_tenant__94a382_idx',
            old_name='detection_d_tenant__868681_idx',
        ),
        migrations.AlterUniqueTogether(
            name='allowlistrule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='allowlistrule',
            name='domain',
            field=models.CharField(blank=True, help_text="Exact host match, e.g. 'api.stripe.com'.", max_length=255),
        ),
        migrations.AddField(
            model_name='allowlistrule',
            name='domain_suffix',
            field=models.CharField(blank=True, help_text="Suffix host match, e.g. '.stripe.com' or 'stripe.com'.", max_length=255),
        ),
        migrations.AddField(
            model_name='allowlistrule',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('feedback', 'Feedback')], default='manual', help_text="How this rule was created — 'manual' from API/admin, 'feedback' from user verdicts.", max_length=20),
        ),
        migrations.AddField(
            model_name='dataevent',
            name='decision_reason',
            field=models.CharField(blank=True, help_text="Machine-parseable 'namespace:detail' reason emitted by the classifier.", max_length=255),
        ),
        migrations.AddField(
            model_name='dataevent',
            name='outcome',
            field=models.CharField(choices=[('expected', 'Expected'), ('acceptable', 'Acceptable'), ('suspicious', 'Suspicious'), ('prohibited', 'Prohibited')], default='expected', help_text='Deterministic classification of (asset, sink) — see detection.classifier.', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='allowlistrule',
            unique_together={('tenant', 'asset_name', 'endpoint_prefix', 'domain', 'domain_suffix')},
        ),
    ]
