# Generated by Django 5.2.13 on 2026-04-22 18:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiregraph_egress', '0001_initial'),
        ('wiregraph_tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalservice',
            name='accepts_assets',
            field=models.JSONField(blank=True, default=list, help_text="Asset names this sink is expected to receive, e.g. ['email','person_name']."),
        ),
        migrations.AddField(
            model_name='externalservice',
            name='category',
            field=models.CharField(choices=[('payments', 'Payments'), ('llm', 'LLM'), ('analytics', 'Analytics'), ('crm', 'CRM'), ('email_provider', 'Email provider'), ('sms', 'SMS'), ('auth', 'Auth'), ('logging', 'Logging'), ('storage', 'Storage'), ('cdn', 'CDN'), ('internal', 'Internal'), ('unknown', 'Unknown')], default='unknown', help_text='Sink category populated from the sink catalog on first sight.', max_length=32),
        ),
        migrations.AddField(
            model_name='externalservice',
            name='trust_tier',
            field=models.CharField(choices=[('trusted', 'Trusted'), ('known', 'Known'), ('unknown', 'Unknown')], default='unknown', help_text='How much trust the classifier grants this sink.', max_length=16),
        ),
        migrations.CreateModel(
            name='SinkCatalogOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_suffix', models.CharField(help_text="Suffix to match, e.g. 'stripe.com' or 'api.internal.corp'.", max_length=255)),
                ('category', models.CharField(choices=[('payments', 'Payments'), ('llm', 'LLM'), ('analytics', 'Analytics'), ('crm', 'CRM'), ('email_provider', 'Email provider'), ('sms', 'SMS'), ('auth', 'Auth'), ('logging', 'Logging'), ('storage', 'Storage'), ('cdn', 'CDN'), ('internal', 'Internal'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('trust_tier', models.CharField(choices=[('trusted', 'Trusted'), ('known', 'Known'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('accepts_assets', models.JSONField(blank=True, default=list, help_text="Empty list means 'use category default'; omit assets to accept nothing.")),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='wiregraph_tenants.tenant')),
            ],
            options={
                'verbose_name': 'Sink Catalog Override',
                'verbose_name_plural': 'Sink Catalog Overrides',
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('tenant', 'domain_suffix')},
            },
        ),
    ]
