# Generated by Django 5.2.13 on 2026-04-12 01:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detection', '0001_initial'),
        ('egress', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('legal_basis', models.CharField(blank=True, help_text='GDPR Article 6 legal basis — user-enriched', max_length=255)),
                ('retention_period', models.CharField(blank=True, help_text='Data retention period — user-enriched', max_length=255)),
                ('dpo_contact', models.CharField(blank=True, help_text='Data Protection Officer contact — user-enriched', max_length=255)),
                ('data_assets', models.ManyToManyField(blank=True, related_name='processing_activities', to='detection.dataasset')),
                ('external_services', models.ManyToManyField(blank=True, related_name='processing_activities', to='egress.externalservice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Processing Activity',
                'verbose_name_plural': 'Processing Activities',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
