# Generated by Django 4.2.11 on 2026-05-03 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wiregraph_reporting", "0003_escalation_digest"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="alertdigestentry",
            new_name="wiregraph_r_tenant__cf9795_idx",
            old_name="wiregraph_r_tenant__digest_idx",
        ),
        migrations.RenameIndex(
            model_name="escalationcounter",
            new_name="wiregraph_r_tenant__d2d2ef_idx",
            old_name="wiregraph_r_tenant__esc_idx",
        ),
        migrations.RenameIndex(
            model_name="shadowdecisioncounter",
            new_name="wiregraph_r_tenant__f7b11d_idx",
            old_name="wiregraph_r_tenant__shadow_idx",
        ),
    ]
